### ISSUE TITLE
Create loading/waiting for the matchmaking process

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#15] opened 2022-04-25 06:07 UTC
## Description

When the player is waiting feedback from the server we should show a waiting for the player. 
Here is Gokus (US) and Demi (Asia) difference: https://www.loom.com/share/91f5b48b19cc4ae9b06c09cced5dd69f
Servers are in US so everthing works faster there. 

Check out other games and come up with a simple design for this 

## Resources
- ### [Competitive Analysis / Matchmaking&Loading](https://user-images.githubusercontent.com/90673012/166965789-50b71022-c423-4e5e-86c2-0afabbcbca02.png)

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by goktugyil** [comment] 2022-04-25 15:17
the feedback and reaction have seemless transitions between each other.

so if we have a loading UI, it should look natural when it suddenly starts showing new data

**Comment by samgawaran** [comment] 2022-05-04 08:06
to clarify:

> the feedback and reaction have seamless transitions between each other.

Feedback = Matchmaking Loading

Reaction = ![image](https://user-images.githubusercontent.com/90673012/166643703-09c09f84-4eb5-40e7-a975-01a6640f490f.png)

**Comment by demiculus** [comment] 2022-05-04 08:49
> Should I research some samples for both Matchmake Loading and Finding a Game or retain the current loading screen and find a good launching screen to fit that?

Always do research before implementing.

**Comment by samgawaran** [comment] 2022-05-05 16:25
#### Recommendations based on research:

Check this [competitive analysis](https://user-images.githubusercontent.com/90673012/166965789-50b71022-c423-4e5e-86c2-0afabbcbca02.png) for more info. Recommended quick solutions for this since it needs to work well with our existing matchmaking flow. 

![image](https://user-images.githubusercontent.com/90673012/166968809-9649e34e-3dd7-4b6f-a2f1-be339d2760b6.png)

I'll create the prototypes later to polish my proposals and explain the flow better. 

Got some ideas for the matchmaking screen while researching. let me know if you want me to explore that on another issue

**Comment by samgawaran** [comment] 2022-05-06 05:19
### For Review: @demiculus @goktugyil @JuanRoman77 

https://www.loom.com/share/7b3f257a1a214c9da692714044009a6f

**Comment by JuanRoman77** [comment] 2022-05-06 05:45
The delay is too small to requiere a loading animation, which would add more stuff to the interface and most likely more delays.
This should be fixed by optimizing the code, not by adding more stuff. It should first check if the player has logged in and then attempt to matchmake, not the other way around. Something like this would remove all delays, weird popup behaviour, and action canceling animations.

I'm sure @JeffdEon can think of something better since he coded it in the first place.

**Comment by goktugyil** [comment] 2022-05-07 01:33
@demiculus leaving this with you

**Comment by JeffdEon** [comment] 2022-05-07 11:01
> which would add more stuff to the interface and most likely more delays.

Incorrect, adding a loading screen would not increase delay. It just shows you something in the UI so you know its responding. Nothing in the backend is delayed.

> I'm sure @JeffdEon can think of something better since he coded it in the first place.

This isn't a code problem. This is a globalization problem. Demi sees more lag than we do because he's on the other side of the world. 

> It should first check if the player has logged in and then attempt to matchmake, not the other way around.

The code is checking if they're logged in before matching. The delay is in connecting demi to the server. We can change it to an API call but then it delays things even more since establishing connection would be pushed back in the pipeline.

Current logic:

- Click (show dummy popup in frontend) => establish connection to server => check player status (throw error if there's a problem) => start finding game

The problem is the `show dummy popup in frontend` part of it. The code is checking before matching, but because the popup shows up first the player doesn't think this is happening. So the idea was to show a loading screen so they know something is happening (establishing connection to server).

**Comment by JeffdEon** [comment] 2022-05-07 11:04
As Goku said, we should leave it to Demi. He's the one experiencing lag. If the lag is too small then let's just remove the dummy popup.

I would imagine someone on the other side of the world with bad internet probably has more of a delay.

**Closed** 2022-05-07 15:41 UTC
Labels: 1: High
